name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON, create themes, export css
      - run: npm run build-tokens
      # Build react app
      - run: npm run build
      # Commit files that were created by the workflow to the git repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
